### ISSUE TITLE
Release and install information

### ISSUE THREAD

**Issue by gasparakos** [dpvreony/wsussmartapprove#3]
**Is your feature request related to a problem? Please describe.**
Is there any compiled version to download, or instructions how to compile this project? 

**Describe the solution you'd like**
Add releases to repository, or extend Readme with compile instructions.

Thank You!

**Comment by dpvreony** [comment]
i'll have to update it. i've not done an external release since this was moved off codeplex

**Comment by dpvreony** [comment]
updated the documentation link. sorting the CI build out to run on Windows 10 and Server 2019. will be a few days

**Comment by TimoBekon** [comment]
Are there any updates on this? Would love to give this software a try, but without any nformation on how to compile, it's difficult. It'd be great if you could give a quick hint, e.g. on the used toolchain.

**Comment by dpvreony** [comment]
apologies will take a look. covid work is taking up a lot of my time. the build script was updated

``Install-WindowsFeature UpdateServices-API``

is the key piece required along with Visual studio

**Comment by dpvreony** [comment]
i've put a release up. it's no different from the one from codeplex back in 2014 other than it has been moved up to net48. the old instructions are on https://dpvreony.github.io/wsussmartapprove/

**Comment by TimoBekon** [comment]
I had trouble compiling this repository along with Visual Studio, but your provided release works like a charme. Thank you very much for your effort!
